### ISSUE TITLE
Are you open to add other repositories? 

### ISSUE THREAD

**Issue by kakawait** [AerisCloud/ansible-repos#15]
Your ansible role is quite simple but really helpful. Nevertheless you just support a definite list of repositories.

Two solutions:
1. Are you open to add other repository? Like MySQL-community official repository
2. May possible to add custom repository via defaults variables.

**Comment by MiLk** [comment]
Hello,

Yes, it's possible to include other official repositories.
See https://github.com/AerisCloud/ansible-repos/pull/9 for example.

For CentOS, it's possible to specify custom repositories with the `remote_repositories` variable.
For Debian, you should use the [apt_repository](http://docs.ansible.com/ansible/apt_repository_module.html) module.

Feel free to submit a PR :)

**Comment by MiLk** [comment]
Closing this issue, as the repo has been added.
